"""2nd

Revision ID: 12b896306c24
Revises: None
Create Date: 2016-06-14 13:56:32.143000

"""

# revision identifiers, used by Alembic.
revision = '12b896306c24'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
