"""3th

Revision ID: 3adff10e0cf2
Revises: 12b896306c24
Create Date: 2016-06-14 16:15:04.935000

"""

# revision identifiers, used by Alembic.
revision = '3adff10e0cf2'
down_revision = '12b896306c24'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
