"""10d

Revision ID: 3d5192a3101c
Revises: 9c81ab459b17
Create Date: 2016-06-21 11:26:52.665000

"""

# revision identifiers, used by Alembic.
revision = '3d5192a3101c'
down_revision = '9c81ab459b17'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
