"""itsdangerous

Revision ID: d2cf8984fc57
Revises: 3adff10e0cf2
Create Date: 2016-06-15 13:19:20.745000

"""

# revision identifiers, used by Alembic.
revision = 'd2cf8984fc57'
down_revision = '3adff10e0cf2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
