"""11f

Revision ID: eac3f1ded14a
Revises: d7f87678f7f5
Create Date: 2016-06-23 09:35:57.145000

"""

# revision identifiers, used by Alembic.
revision = 'eac3f1ded14a'
down_revision = 'd7f87678f7f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
